### ISSUE TITLE
Add new functions 'CheckSpatialIdsOverlap', 'CheckSpatialIdsArrayOverlap', 'CheckExtendedSpastialIdsArrayOverlap' and 'CheckExtendedSpastialIdsOverlap'

### ISSUE THREAD

**Issue by hikata101** [trajectoryjp/spatial_id_go#12]
**Describe the solution you'd like**

- CheckSpatialIdsOverlap would provide a method for checking the overlap between two spatialIds.
- CheckSpatialIdsArrayOverlap would provide a method for checking the overlap between two arrays of spatialIds.

- CheckExtendedSpatialIdsOverlap would provide a method for checking the overlap between two extended spatialIds.
- CheckExtendedSpatialIdsArrayOverlap would provide a method for cheking the overlap between two arrays of extended spatialIds.

**Comment by HarutakaMatsumoto** [comment]
I merged the pull request.
Thank you for your contribution.
I wish you continued success!👍
