### ISSUE TITLE
Append conversion functions between ExtendedSpatialId and QuadkeyAndAltitudekey without using floating point numbers

### ISSUE THREAD

**Issue by HarutakaMatsumoto** [trajectoryjp/spatial_id_go#21]
**Is your feature request related to a problem? Please describe.**
For example, we can convert ExtendedSpatialId to QuadkeyAndAltitudekey with ConvertExtendedSpatialIDsToQuadkeysAndVerticalIDs(_).
However, this uses floating point numbers for the maximum and minimum heights, which can lead to calculation errors.

**Describe the solution you'd like**
QuadkeyAndAltitudekey has the same measurements as ExtendedSpatialId, so ideally we can convert between them without using floating point numbers.

**Describe alternatives you've considered**
Please append conversion functions between ExtendedSpatialId and QuadkeyAndAltitudekey without using floating point numbers.

**Additional context**
This blocks #17.

**Comment by buscandoaverroes** [comment]
memo:
- I won't use min/max at all but instead use scalar (int64) in input parameters, and offset (int64) to convert BitIndexes

**Comment by HarutakaMatsumoto** [comment]
I accepted #22 .
Thank you for your contribution!
