### ISSUE TITLE
Make ConvertExtendedSpatialIdsToQuadkeysAndAltitudekeys() easier to use

### ISSUE THREAD

**Issue by buscandoaverroes** [trajectoryjp/spatial_id_go#23]
**Is your feature request related to a problem? Please describe.**
the current input parameters are:

```
ConvertExtendedSpatialIDsToQuadkeysAndAltitudekeys
//
//	Converts ExtendedSpatialIDs to []*object.FromExtendedSpatialIDToQuadkeyAndAltitudekey given zoom, scalar and offset parameters
//
// input:
//
// extendedSpatialIDs: slice of string-encoded ExtendedSpatialIDs
//
// outputQuadkeyZoom: the horizontal resolution of the output
//
// outputAltitudekeyZoom: the vertical resolution of the output
//
// altitudeRangeScalar: altitude range scalar is s, where 2^25-s = altitude range (max altitude - min altitude)
//
// verticalIndexOffset : shifts the altitude range up or down by n units of the resulting verticalIndex

```
but `altitudeRangeScalar` and `verticalIndexOffset` should be easier to understand and implement. `altitudeRangeScalar` requires two-step calculation (2^25 - 2^scalar) and `verticalIndexOffset` changes depending on `outputAltitudekeyZoomLevel`. 

**Describe the solution you'd like**

- `verticalIndexOffset` should ideally be intuitive and independent of other input parameters (ie, not dependent on the outputAltitudekeyZoom)
- `altitudeRangeScalar` should simply be 2^scalar

**Comment by HarutakaMatsumoto** [comment]
I coped with it.
