### ISSUE TITLE
Use TileXYZ instead of QuadkeysAndAltitudekeys

### ISSUE THREAD

**Issue by mi-24v** [trajectoryjp/spatial_id_go#28]
**Is your feature request related to a problem? Please describe.**

There is overhead about converting QuadKey into 3D-tile key index.

Spatial ID uses f, x and y independently.
While both 3D-tile key index and QuadkeysAndAltitudekeys have [z-order](https://en.wikipedia.org/wiki/Z-order_curve) feature, QuadkeysAndAltitudekeys causes convert between QuadKey and 3D-tile key for using independent indices.
This conversion is not essential and has overhead.

**Describe the solution you'd like**

QuadkeysAndAltitudekeys needs to replace into TileXYZ

**Describe alternatives you've considered**

It is breaking change because backward compatibility will be broken if QuadkeysAndAltitudekeys are deleted totally.
It needs transition duration.

**Additional context**

(nothing)

**Comment by HarutakaMatsumoto** [comment]
This issue is coped with.
